### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alcalyn** [socketio/chat-example#10]
Hi, I'll maybe use this code or snippet from this.

I can't see any license, so for now it means it's closed by default.

Is is free software ?

**Comment by jash101** [comment]
Yes. You can use this code for your project

**Comment by nibalizer** [comment]
It would still be pretty cool to be explicit about licensing it under something like Apache 2. We'd appreciate it!

**Comment by darrachequesne** [comment]
The code is licensed under the MIT License. I added the license in the repository to make it clearer (https://github.com/socketio/chat-example/commit/68fd421da015369eec9dd356cc21b6f50bbf4ee9).
