### ISSUE TITLE
App can't run on another project folder

### ISSUE THREAD

**Issue by lcheewei** [socketio/chat-example#11]
I am able to run the sample app downloaded from the following website: https://github.com/socketio/chat-example

However when I try to copy the index.js and index.html file to my existing project folder, the app can't seem to run. have also installed the dependencies:
- npm install --save express@4.15.2
- npm install --save socket.io

May I missing other files/ dependencies?

**Comment by Nevin1901** [comment]
index.html is not the only thing you need. You also need to copy over main.js, style.css, ect.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
