### ISSUE TITLE
socket.io 2.0.4?

### ISSUE THREAD

**Issue by rayj00** [socketio/chat-example#13]
Will this run on socket.io v2.0 and later?

**Comment by jamiesonbecker** [comment]
No, but try:

```
sudo npm uninstall socket.io
npm install --save socket.io=1.4.5
```

**Comment by artemean** [comment]
I updated both client and server to 2.0.4 and now I see huge delays in the response from the server. I send a message from one tab and updates fire in 2-10s in all tabs, sometimes 20s. But if I keep sending messages quickly they are coming thru except the last one which comes with a delay.
Another strange thing is if I have only one tab open with the chat it works fine, but what's the point in talking to yourself? :-)
With 1.7.3 it works perfectly fine. What is wrong with 2.0.4?

**Comment by kenwithee** [comment]
@artemean  - I am experiencing the exact same behavior. I was thinking to go through the Chat App sample and get it to work with 2.0.4 socket.io. I haven't figured out what is causing the issue yet though. If anyone figures out please update us on this issue so we can submit a PR and fix. :)

**Comment by kenwithee** [comment]
After playing around with this there seems to be something conflicting with the single `var socket = io();` variable. When I add a second one with `var socket2 = io();` and use the second one with consuming the socket it seems to work. I am still figuring out what could be conflicting though but thought I would pass this along.

**Comment by artemean** [comment]
@kenwithee I fixed this problem in my server code.
`const io = require('socket.io')(httpServer, { wsEngine: 'ws' });`
I found this solution in the main repo [issue](https://github.com/socketio/socket.io/issues/3179#issuecomment-368258717).

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/chat-example/commit/c16c98540d43c4ad5033aadf7cc2df468f1b9652.

Note: the chat example will work for every Socket.IO version, provided that you use compatible versions on the server and on the client (2.x client <=> 2.x server, 3.x client <=> 3.x server, ...)
