### ISSUE TITLE
how can we get this file "socket.io.js"

### ISSUE THREAD

**Issue by lanix516** [socketio/chat-example#15]
In the expamle,  index.html 
<script src="/socket.io/socket.io.js"></script>
and then we can use io, but i don't understand how can we get this file in my localserver without any setting, the real url is 'http://127.0.0.1:3000/socket.io/socket.io.js'.
this problem has plagued me for a long time, thank U

**Comment by awais786327** [comment]
@lanix516 simply you can run npm i socket.io and then give your destination path starting from **/socket.io/socket.io.js** into your app

**Comment by lanix516** [comment]
Yes, i hava already run 'npm i socket.io', and the whole app just run fine.
which i really don't understand is how this url ('http://127.0.0.1:3000/socket.io/socket.io.js'.) link to the file in   'node_modules/socket.io/node_modules/socket.io-client/dist/socket.io.js'.

how does the example deal with static file.

thanks

**Comment by lanix516** [comment]
find it!
var io = require('socket.io')(http);
the static file setting in Server.serveClient.
sorry for disturb and thank u
