### ISSUE TITLE
cros problem

### ISSUE THREAD

**Issue by huzhenjie** [socketio/chat-example#18]
The example has `Access-Control-Allow-Origin` problem.

I just edit `index.html`

```
var socket = io('http://localhost:3000');
```

Then the Chrome Console print like this

```
Failed to load http://localhost:3000/socket.io/?EIO=3&transport=polling&t=1521768422803-4: The 'Access-Control-Allow-Origin' header has a value 'null' that is not equal to the supplied origin. Origin 'null' is therefore not allowed access.
```

**Comment by rajatsaini736** [comment]
In your server-side, where you initialize your `io` variable allow cors as : 
var io = require('socket.io')(server, {
  cors: {
    origin: '*',
  }
});

**Comment by darrachequesne** [comment]
Please see the documentation here: https://socket.io/docs/v3/handling-cors/
