### ISSUE TITLE
Works, but cannot be connected to using a public IP.

### ISSUE THREAD

**Issue by SkyHawkB** [socketio/chat-example#20]
What the title says. I have copied and slightly modified the code. It works as intended, but I can only connect from the machine it is running on (using `localhost:3000` or `192.168.1.3:3000`). I have attempted to use port forwarding but it did not help the issue. I'd like to know how I can make the app accessible from another machine, and if it is possible to host the app on GH Pages.

**Comment by maxrumsey** [comment]
Not so sure about the port forwarding (seems to be a problem on your end) and you won't be able to host the server on gh pages.

**Comment by SkyHawkB** [comment]
I should've closed this...
