### ISSUE TITLE
blank - no texts sent or received

### ISSUE THREAD

**Issue by donitel** [socketio/chat-example#21]
I tried copying and pasting the code and run the application. I checked the: " io.on('connection', function(socket){ " part and it works when a user connects. But the other part of " socket.on..... " doesn't seem to be working. When I enter texts in the form I get blank on the client page and the server is blank as well. I tried to test it by typing console.log to display something when "socket.on" gets fired, but nothing shows up. What's missing? Can anyone please help? 

Thanks

**Comment by bcolflesh** [comment]
Yeah, this example doesn't work anymore - as you can test by using the example in the readme:

https://socketio-chat-example.now.sh/

**Comment by bcolflesh** [comment]
You can fix by making the change shown here:

https://github.com/socketio/chat-example/pull/16/files

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/chat-example/commit/c16c98540d43c4ad5033aadf7cc2df468f1b9652 (ensure the client and server versions match).
