### ISSUE TITLE
Multiple socket.ids generated

### ISSUE THREAD

**Issue by bosna387** [socketio/chat-example#22]
This code is not working alrite....multiple socket.ids generated from the same tab. So sometimes client connects to himself or others connect to non existing client.

**Comment by lowtolerance** [comment]
Socket.id identifies the connection, not the client or the session. If you are being assigned multiple ids, it is because you are connecting multiple times.

**Comment by darrachequesne** [comment]
Please see the documentation here: https://socket.io/docs/v3/client-socket-instance/

**Comment by Kiisi-Felix-Destiny** [comment]
hello
I have some challenges
Socket.io is generating its ID multiple times
