### ISSUE TITLE
Getting started outdated version

### ISSUE THREAD

**Issue by kordix** [socketio/chat-example#30]
I wasted around 2 hours wondering why it's not working when I did everything like in this tutorial:
https://socket.io/get-started/chat/
I downloaded code from github. Copied everything from index.js - not working, everything from index.html - not working. Then I look to package.json - damn, that's some old one. Finally when I copied package.json and reinstalled it started working.

But I can't get it going with newest version because... tutorial is just shi**y, sorry

**Comment by jonahcrowlinson** [comment]
Same here...

Thanks for the package.json idea

**Comment by kordix** [comment]
I realized something- the source courde on github included outdated client version of socket.io, that's why it wasn't working for newest package.json
But it still misleading anyway

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/chat-example/commit/c16c98540d43c4ad5033aadf7cc2df468f1b9652
