### ISSUE TITLE
the deployed application is crashing: zeit wants 💰

### ISSUE THREAD

**Issue by marclundgren** [socketio/chat-example#31]
1. navigate to https://socketio-chat-example.now.sh/

<img width="956" alt="Screen Shot 2019-08-28 at 12 23 34 PM" src="https://user-images.githubusercontent.com/1154834/63886144-ae667500-c98e-11e9-9a99-834f7672123b.png">

**Comment by darrachequesne** [comment]
That should be fixed now. Thanks for the heads-up! :ok_hand:

**Comment by PDanielY** [comment]
@darrachequesne Close issue?
