### ISSUE TITLE
Messaging is not working

### ISSUE THREAD

**Issue by jaymeen1** [socketio/chat-example#35]
In this project some i get is 
First one is Two user are connected then it's not get alert or any type of other suggestion
Second one is when user click on the send button then the message not send or not show in any place like a nothing to see just realise  message was send but which place send it's not see

SO i need some help please

any one do this then tell me i'm still waiting for a good developer

**Comment by twilighthook** [comment]
The project int index.html should use another socketjs version, like 
https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.1.1/socket.io.js

otherwise, it will cause infinite loop at connection

**Comment by jaymeen1** [comment]
Thank you @twilighthook 
now it's working but second problem is show

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
