### ISSUE TITLE
getting CORS errors on firefox

### ISSUE THREAD

**Issue by ppazos** [socketio/chat-example#39]
added origins but got the same problem

var io = require('socket.io')(http, {origins: '*:*'});

**Comment by HexDevv** [comment]
That's meant to be in your backend node.js server

**Comment by ppazos** [comment]
@HexDevv that is on my backed. Couldn't find much info on socket.io docs on how to configure CORS correctly.

**Comment by darrachequesne** [comment]
Please see https://socket.io/docs/v3/handling-cors/
