### ISSUE TITLE
Example doesn't work anymore

### ISSUE THREAD

**Issue by kekerooo** [socketio/chat-example#42]
Hi,
The example, if you install express and socket.io via 

> npm install express socket.io

,doesn't work anymore, because the client _index.html_ file references to an old socket.io version.

For me, the browser opens a lot of connection every second instead of keeping one.

If i change the script on the index.html to _https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js_ it works again flawlessly.

BR 
kekerooo

**Comment by tap6** [comment]
Cool man

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/chat-example/commit/c16c98540d43c4ad5033aadf7cc2df468f1b9652.
