### ISSUE TITLE
What package should I get?

### ISSUE THREAD

**Issue by kindkmj** [socketio/chat-example#47]
i use pacaage
npm i socket.io 
npm i express    

![스크린샷 2020-06-23 오전 11 45 52](https://user-images.githubusercontent.com/41276448/85355241-22d65a00-b547-11ea-988a-33ec123f1cb5.png)

I downloaded the package and received a lot of requests like an image.
What package should we apply?
The code is the same as the original code.

**Comment by guptapriyanshu7** [comment]
Change the script on the index.html to https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js it should work again.

**Comment by darrachequesne** [comment]
I think this is due to a mismatch between the version of the client and the one of the server. This should be fixed by https://github.com/socketio/chat-example/commit/c16c98540d43c4ad5033aadf7cc2df468f1b9652.
