### ISSUE TITLE
Get the request URL in the index.js

### ISSUE THREAD

**Issue by Andrewyg** [socketio/chat-example#5]
I have make a new variable call httpd and named it as `var httpd = require('http');` and I use it to create and get the client request file, and now I want to emit a value when someone visit `/greet` path it will emit to chat room so I add this before `io.on` code
I add the following code
    var httpd = require('http);
    var path;
    httpd.createServer(function (req, res) {
      path = req.url;
    };
    if (path == "/greet") {
      io.on ....

But the code doesn't emit a value to chatroom when someone visit /greet
What I'm missing?
Or we can't get `req.url` in socket.io code?

**Comment by andreasvirkus** [comment]
You should create an Express route instead:
```
app.get('/greet', function(req, res) {
  // A user visited '/greet/, do something now
 // like socket.emit()
});
```
