### ISSUE TITLE
Repeated messages

### ISSUE THREAD

**Issue by YodaLightsabr** [socketio/chat-example#55]
![image](https://user-images.githubusercontent.com/76178582/108122304-ec5ec980-7058-11eb-9625-4ea4533495ad.png)
![image](https://user-images.githubusercontent.com/76178582/108122316-f254aa80-7058-11eb-8c19-b885ae2fffd7.png)
Messages are being sent repeatedly, and it's on the client side.

**Comment by Jriera** [comment]
If the code is implemented as it is shown in the repo this does not happen. 
This might be helpful if you coded it by yourself: [StackOverflow](https://stackoverflow.com/questions/17057455/socket-io-firing-multiple-events)
