### ISSUE TITLE
Missing line of code in the get started guide

### ISSUE THREAD

**Issue by Guneetsinghtuli** [socketio/chat-example#61]
You Must include `<script src="/socket.io/socket.io.js"></script>` before the other script otherwise it wont work.

![Screenshot 2021-12-21 at 1 05 44 AM](https://user-images.githubusercontent.com/48324492/146822892-178e1edb-8983-4d4b-b704-cab5c0aec977.png)

**Comment by darrachequesne** [comment]
You are right, the page was a bit misleading. That should be fixed now :+1:
