### ISSUE TITLE
form.addEventListener is not a function

### ISSUE THREAD

**Issue by Pedr0Leite** [socketio/chat-example#73]
I'm getting this error about the form addEventListener and I can't understand why.
I already tried to copy the code and still get the same error.

Uncaught TypeError: form.addEventListener is not a function
    at index.js:10:6

`var socket = io();

var input = document.getElementById('input');
var roomInput = document.getElementById('room-input');
var messages = document.getElementById('messages');
var form = document.getElementById('form');

form.addEventListener('submit', function(e) {
  e.preventDefault();
  if (input.value) {
    socket.emit('chat message', input.value);
    input.value = '';
  }
});

socket.on('chat message', function(msg){
    var item = document.createElement('li');
    item.textContent = msg;
    messages.appendChild(item);
    window.scrollTo(0, document.body.scrollHeight);
});`

Can you help me, please?

Regards!
Pedro

**Comment by darrachequesne** [comment]
Hi! This might happen if there is no element with id  ̀form` in your html page (like [here](https://github.com/socketio/chat-example/blob/3c7903c2d0aaaa660edaf5d0b07375fe00224011/index.html#L20)). Could you please check?

**Comment by darrachequesne** [comment]
Hmm, that's weird. Have you found the culprit?

**Comment by MarcJoyce** [comment]
> I'm getting this error about the form addEventListener and I can't understand why.
> I already tried to copy the code and still get the same error.
> 
> Uncaught TypeError: form.addEventListener is not a function
>     at index.js:10:6

Is this a typo or have you put the form.addEventListener to your index.js file instead of index.html?

**Comment by Pedr0Leite** [comment]
Hello @darrachequesne,

Thank you for your support, I've found the issue.
The script tag on the html has to be on the end, after the body tag, after the whole HTML is processed so the script can take the info from it (it was on top, so when it ran, it didn't found any tag referenced on the html)

And thats it!

Thank you so much!

Regards,
Pedro
