### ISSUE TITLE
Sample app does not work because client socket.io version is hard-coded from a CDN

### ISSUE THREAD

**Issue by jfriend00** [socketio/chat-example#8]
In [this sample app](https://github.com/socketio/chat-example/blob/master/index.html#L22), it hard codes a CDN reference to v1.2 of socket.io.  When someone tries to implement this sample app and the current version of socket.io that they are using on their server is no longer 1.2, it does not work and it is difficult to figure out why.  I would think the script tag should be `<script src="/socket.io/socket.io.js"></script>` so that it always loads the right version of the client.  For an example of how confused a socket.io newbie gets when this happens see [this question/answer](https://stackoverflow.com/questions/45807517/socket-io-not-sending-to-client/45808034#comment78574117_45808034) on stackoverflow.

**Comment by kenklin** [comment]
jfriend00's fix above matches the "Emitting Events" text at https://socket.io/get-started/chat/

**Comment by Qudusayo** [comment]
Try using  the hard-code value from the node_modules file
```js
app.use(epress.static(__dirname + '/node_modules'))
```

```html
<head>
     <script src="socketio/socket.io.js"></script>
</head>
```

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/chat-example/commit/c16c98540d43c4ad5033aadf7cc2df468f1b9652.
